Language = {

    --# Resource 

    Anti_Fake_Chat_Message = 'Anti Fake Chat Message',
    Anti_BlackListed_Chat_Word = 'Anti BlackListed Chat Words: %s',
    Anti_Chat_Spam = 'Anti Chat Spam: %s',
    Anti_Trigger = 'Anti Trigger: %s',
    Anti_Exports_Use = 'Anti Export Use: %s - %s',
    Anti_Menyoo = 'Anti Menyoo',
    Anti_Mass_Trigger_Use = 'Anti Trigger Spam: %s',
    Anti_Executor = 'Anti Executor: %s',
    Anti_Solo_Session = 'Anti Solo Session',
    Anti_Dump = 'Anti Dump',
    Anti_Sound_Play = 'Anti Sound Player',
    Anti_Resource_Stop = 'Anti Resource Stop: %s',
    Anti_Trigger_Client_Event = 'Anti Trigger Client Event: %s - %s',

    --# General

    ConnectingMessage = 'Hello, %s\n Checking and securing your data ...',
    Welcome = 'Welcome to Parazia RP',
    Ban = 'You have been definitively banned from Parazia RP\n👀 Ban Reason: %s\n⛔ Ban ID: %s\n🚀 Author: %s',
    HiddenBan = 'You have been definitively banned from Parazia RP for cheating\n⛔ Ban ID: %s',
    HiddenKick = 'You have been kicked from Parazia RP for cheating',
    Kick = 'You have been kicked from Parazia RP\n👀 Kick Reason: %s\n🚀 Author: %s\n',  

    Anti_BlackListed_Player_Name = 'Anti BlackListed Name: %s',
    Anti_Null_Tokens = 'Impossible de récupérer vos tokens, redemarrer fivem peut aider à résoudre ce problème',
    Anti_BlackListed_Leave_Reason = 'Anti BlackListed Leave Reason: %s',

    Anti_Clear_Ped_Task = 'Anti Clear Ped Task',
    Anti_BlackListed_Task = 'Anti BlackListed Task: %s',
    Anti_Radar = 'Anti Radar',
    Anti_Give_Armor = 'Anti Give Armor: %s',
    Anti_BlackListed_Texture = 'Anti BlackListed Texture: %s',
    Anti_Night_Vision = 'Anti Night Vision',
    Anti_Thermal_Vision = 'Anti Thermal Vision',
    Anti_Afk_Bypass = 'Anti Afk Bypass',
    Anti_Small_Player_Ped = 'Anti Small Player Ped',
    Anti_Super_Jump = 'Anti Super Jump',
    Anti_Infinite_Stamina = 'Anti Infinite Stamina',
    Anti_Fast_Run = 'Anti Fast Run: %s',
    Anti_NoClip = 'Anti NoClip',
    Anti_Not_Script_Cam_Spawn = 'Anti Not Script Cam Spawn: %s',
    Anti_Spectate = 'Anti Spectate',
    Anti_Blips = 'Anti Blips',

    --# Weapon 

    Anti_Infinite_Ammo = 'Anti Infinite Ammo',
    Anti_Give_Weapon_To_Player = 'Anti Give Weapon To Player: %s',
    Anti_Remove_Weapon_From_Player = 'Anti Remove Weapon From Player: %s',
    Anti_Remove_All_Weapons_From_Player = 'Anti Remove All Weapons From Player',
    Anti_Shot = 'Anti Shot: %s',
    Anti_Mass_Shot = 'Anti Mass Shot: %s',
    Anti_Explosive_Weapon = 'Anti Explosive Weapon',
    Anti_BlackListed_Weapon = 'Anti BlackListed Weapon: %s',
    Anti_Not_Script_Vehicle_Spawn = 'Anti Not Script Vehicle Spawn: %s',
    Anti_Weapon_Defense_Modifier = 'Anti Weapon Defense Modifier: %s',
    Anti_Weapon_Damage_Modifier = 'Anti Weapon Damage Modifier: %s',
    Anti_Melee_Defense_Modifier = 'Anti Melee Defense Modifier: %s',
    Anti_Melee_Damage_Modifier = 'Anti Melee Damage Modifier: %s',
    Anti_Weapon_Clip_Modifier = 'Anti Weapon Clip Modifier: %s',
    Anti_PickUp_Spawn = 'Anti Weapon Pick Up Spawn: %s',

    --# Vehicle 

    Anti_Vehicle_Exploiting = 'Anti Vehicle Exploiting',
    Anti_Mass_Vehicle_Delete = 'Anti Mass Vehicle Delete: %s',
    Anti_BlackListed_Vehicle = 'Anti BlackListed Vehicle: %s',
    Anti_Mass_Vehicle_Spawn = 'Anti Mass Vehicle Spawn: %s',
    Anti_Not_Script_Vehicle_Spawn = 'Anti Not Script Vehicle Spawn: %s',
    Anti_Vehicle_Damage_Modifier = 'Anti Vehicle Damage Modifier: %s',
    Anti_Vehicle_Power_Modifier = 'Anti Vehicle Power Modifier: %s',
    Anti_Vehicle_Top_Speed_Modifier = 'Anti Vehicle Top Speed Modifier: %s',
    Anti_Vehicle_Defense_Modifier = 'Anti Vehicle Defense Modifier: %s',
    Anti_Vehicle_Speed_Modifier = 'Anti Vehicle Speed Modifier: %s',

    --# Ped 

    Anti_Not_WhiteListed_Ped = 'Anti Not WhiteListed Ped: %s',
    Anti_Mass_Ped_Spawn = 'Anti Mass Ped Spawn: %s',
    Anti_Not_Script_Ped_Spawn = 'Anti Not Script Ped Spawn: %s',
    Anti_Not_WhiteListed_Player_Ped = 'Anti Not WhiteListed Player Ped: %s',

    --# Object 

    Anti_Not_WhiteListed_Object = 'Anti BlackListed Object: %s',
    Anti_Mass_Object_Spawn = 'Anti Mass Object Spawn: %s',
    Anti_Not_Script_Object_Spawn = 'Anti Not Script Object Spawn: %s',

    --# Explosion 

    Anti_Mass_Explosion_Spawn = 'Anti Mass Explosion Spawn: %s',
    Anti_Not_WhiteListed_Explosion = 'Anti BlackListed Explosion: %s',
    Anti_Mortal_Explosion = 'Anti Mortal Explosion',
    Anti_Silent_Explosion = 'Anti Silent Explosion',
    Anti_Invisible_Explosion = 'Anti Invisible Explosion',
    Anti_Camera_Shake_Explosion = 'Anti Camera Shake Explosion',

    Anti_Not_WhiteListed_Particle = 'Anti Not WhiteListed Particle Spawn: %s',
    Anti_Mass_Particle_Spawn = 'Anti Mass Particle Spawn: %s',

    Anti_Not_WhiteListed_Projectile = 'Anti Not WhiteListed Projectile Spawn: %s',
    Anti_Mass_Projectile_Spawn = 'Anti Mass Projectile Spawn: %s',

    Anti_Mass_Fire_Spawn = 'Anti Mass Fire Spawn: %s',

    --# FrameWork 

    Anti_Give_Weapon_ESX = 'Anti Give Weapon ESX: %s',

    --# Prints & Messages 

    Print_Ped_Create = '[~g~%s~s~/~g~%s~s~] Just Created a ped: ~y~%s~s~, with the resource: ~y~%s~s~',
    Print_Vehicle_Create = '[~g~%s~s~/~g~%s~s~] Just Created a vehicle: ~y~%s~s~, with the resource: ~y~%s~s~',
    Print_Object_Create = '[~g~%s~s~/~g~%s~s~] Just Created a prop: ~y~%s~s~, with the resource: ~y~%s~s~',
    Print_Explosion_Create = '[~g~%s~s~/~g~%s~s~] Just Created a explosion: ~y~%s~s~',
    Print_Player_Join = 'The player ~g~%s~s~ just joined !',
    Print_Player_Join_Banned = 'The cheater ~r~%s~s~ just tried to join but his banned (BAN ID:~b~%s~s~)',
    Print_Player_Join_Refused = 'The player ~r~%s~s~ connection have been refused for ~y~%s~s~',
    Print_Player_Banned =  '[~g~%s~s~/~g~%s~s~/~g~%s~s~] have been banned by ~y~%s~s~ for ~y~%s~s~ (BAN ID:~b~%s~s~)',
    Print_Player_Kicked = '[~g~%s~s~/~g~%s~s~] have been kicked by ~y~%s~s~ for ~y~%s~s~',
    Print_Player_Left = 'the player %s just left for: %s',
    Print_Anti_Trigger = '[~g~%s~s~/~g~%s~s~] Just used the trigger: ~p~%s~s~',
    Print_Anti_Trigger_Handle = 'The event: ~b~%s~s~ have been successfully handled.',
    
    --# Admin Menu & Command

    Command_Not_Complete = 'Missing data in the command: aerodefence ~r~%s~s~',
    Command_Invalid_Provided_Data = 'Missing data in the command: aerodefence %s, please mention a valid %s',
    Command_Not_Access = 'You don\'t have acces to the command: aerodefence %s',
    Command_Help_Show = 'Here are all the available anti-cheat commands:',
    Command_Help = '~p~aerodefence ~r~%s~s~',
    Command_Console_Only = '~r~Console Only~s~',
    Command_Staff_Only = '~b~Staff Only~s~',
    Command_Public = '~y~Public~s~',
    Command_No_Manifest = 'Failed to retrive the manifest fot the resource: ~b~%s~s~',
    Command_Not_Actif_Ban = 'They are no active bans !',
    Command_Everyone_Unbanned = '[~g~%s~s~ cheater(s)] have been successfully unbanned !',
    Command_Everyone_Unbanned_Log = '**%s cheater(s)** have been unbanned by: **%s**',
    Command_Unknown_Ban_Id = 'their are no ban with the id: ~g~%s~s~',
    Command_Unbanned = '[~g~%s~s~/~g~%s~s~] have been successfully unbanned !',
    Command_Unbanned_Log = '**%s %s** have been unbanned by: **%s** !\nBan Reason: %s\nOriginal Banner: **%s**\nBan Date: **%s**',
    Command_Scan_Started = 'Scan for malicious code has started, please wait until it ends !',
    Command_Scan_Checked = '(~g~%s~s~) Checking resource: [~r~%s~s~/~r~%s~s~]',
    Command_Scan_Safe = 'Your server is safe from malicious code',
    Command_Scan_Not_Safe = 'Malicious code have been found in the resource: ~r~%s~s~, path: ~r~%s~s~',
    Command_Clear = '[~g~%s~s~/~g~%s~s~] ~r~%s~s~ have been successfully deleted from the map',
    Command_Clear_Log = '[**%s**/**%s**] *%s have been successfully deleted from the map by*: **%s**',
    Command_Players = 'The number of connected players is: ~r~%s~s~',
    Command_Menu = 'The admin menu have been successfully opened for: ~r~%s~s~',
    Command_Menu_Notification = 'The admin menu have been opened from the console',
    Command_Menu_Not_Staff = 'The player is not a staff',
    Command_ScreenShot_Id = '~r~%s~s~ have been screenshoted, check logs !',
    Command_ScreenShot_Id_Log = '**%s** *have been screenshoted by:* **%s**',
    Command_ScreenShot_Everyone = '~g~%s~s~ have been screenshoted, check logs !',
    Command_ScreenShot_Everyone_Log = '**%s** *have been screenshoted by:* **%s**',
    Command_Spoof_Started = 'The trigger spoof has started, please wait until it ends !',
    Command_Spoof_Checked = '(~g~%s~s~) Spoofing resource: [~r~%s~s~/~r~%s~s~]',  
    Command_Spoof_Failed_Resource = 'The resource ~r~%s~s~ don\'t exist.',
    Command_Spoof_Sucess = 'The resource ~g~%s~s~ have been successfully spoofed.',
    Command_Whitelist_Already_Whitelisted = '~r~%s~s~ is already whitelisted !',
    Command_Whitelisted = '~r~%s~s~ have been successfully given the group: ~b~%s~s~ !',
    Command_Whitelisted_Received = 'The group: ~b~%s~s~ have been successfully to you !',
    Command_Whitelisted_Notify_Staff = 'The group: ~b~%s~s~ have been successfully to ~r~%s~s~ !',
    Command_Whitelisted_Log = '**%s** have been successfully given the group **%s** by: **%s**',
    Command_Unwhitelist_Not_Whitelisted = '~r~%s~s~ is not whitelisted !',
    Command_Unwhitelisted = '~r~%s~s~ have been successfully removen the group: ~b~%s~s~ !',
    Command_Unwhitelisted_Received = 'The group: ~b~%s~s~ have been removen from you !',
    Command_Unwhitelisted_Notify_Staff = 'The group: ~b~%s~s~ have been removen from ~r~%s~s~ !',
    Command_Unwhitelisted_Log = '**%s** have been successfully removen the group **%s** by: **%s**',
    Command_Banned = '~r~%s~s~ have been successfully banned for: ~g~%s~s~',
    Command_Kicked = '~r~%s~s~ have been successfully kicked for: ~g~%s~s~',
    Command_Vehicle_Created = '~g~%s~s~ have been successfully given a: ~r~%s~s~',
    Command_Vehicle_Log = '**%s** have been given a **%s** by: **%s**',
    Command_Vehicle_Error = 'failed to give a ~g~%s~s~ to ~r~%s~s~',
    Command_Report_Already_Open = 'Sorry, you already have a opened report, please until a staff take care of your situation.',
    Command_Report_Not_Enough = 'please mention a valid report reason',
    Command_Weapon_Failed = 'failed to give a ~g~%s~s~ to ~r~%s~s~',
    Command_Weapon_Succes = '~g~%s~s~ have been successfully given a: ~r~%s~s~',
    Command_Weapon_Log = '**%s** have been given a **%s** by: **%s**',
    Command_AntiDump_Failed = 'failed to retrive a resource with the name: ~g~%s~s~',
    Command_AntiDump_Failed_Cfx = 'failed to install the anti-dump because this resource is ~r~cfx protected~s~',
    Command_AntiDump_Installed = 'Anti Dump have succesfully installed in ~g~%s~s~',
    Command_Stop_Failed = 'The resource ~g~%s~s~ is not started',
    Command_Stop_Succes = 'The resource ~g~%s~s~ have been successfully stopped',
    Command_Stop_Log = 'The resource **%s** have been successfully stopped by: %s',
    Command_Start_Failed = 'The resource ~g~%s~s~ is not stopped',
    Command_Start_Succes = 'The resource ~g~%s~s~ have been successfully started',
    Command_Start_Log = 'The resource **%s** have been successfully started by: %s',
    Command_Restart_Failed = 'The resource ~g~%s~s~ is not started',
    Command_Restart_Succes = 'The resource ~g~%s~s~ have been successfully restarted',
    Command_Restart_Log = 'The resource **%s** have been successfully restarted by: %s',
    Command_AntiStop_Installed = 'The anti-stop have been successfully installed in ~g~%s~s~',
    Command_AntiStop_Already_Installed = 'The anti-stop is already installed in ~r~%s~s~',
    Command_Install_Installed = 'The exports library have been successfully installed in ~g~%s~s~',
    Command_Install_Already_Installed = 'The exports library is already installed in ~r~%s~s~',
    Command_Uninstall_Not_Installed = 'This resource ~g~%s~s~ don\'t have the ~g~%s~s~ installed in.',
    Command_Uninstall_Failed_Resource = 'The resource ~r~%s~s~ don\'t exist.',
    Command_Uninstall_Succes = 'The ~g~%s~s~ have been successfully uninstalled from ~g~%s~s~',

    --# Emojies 

    Emojie_Pin = '📌',
    Emojie_Exclamation = '❗',
    Emojie_BrokenHeart = '💔',
    Emojie_Radar = '📡',
    Emojie_Explosion = '💥',
    Emojie_Check = '✅',
    Emojie_Heart = '💖',
    Emojie_Dollar = '💲',
    Emojie_Wall = '🧱',
    Emojie_Construcation = '🚧',
}
