---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 05/11/2020 02:17
---

local TextPanels = {
    Background = { Dictionary = "kikizizinazi", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 42 },
}

---@type Panel
function JailUI.RenderSrite(Dictionary, Texture)
    local CurrentMenu = JailUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + JailUI.ItemOffset + (JailUI.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            JailUI.StatisticPanelCount = JailUI.StatisticPanelCount + 1
        end
    end
end
