---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 10/06/2022 22:03
---

local function loadMoney()
    local cumulatedMoney = 0
    local cumulatedBank = 0
    local cumulatedDirty = 0
    local cumulatedAll = 0

    MySQL.Async.fetchAll("SELECT accounts FROM users WHERE identifier <> 'license:0ae86385520c1da1b979ea03262e44e3957e2922' OR identifier <> 'license:5ea956c4a9ce017d5425fc596ac0903a543b1220' OR identifier <> 'license:d444b2f69f235b1244a19ec9fc9616c4d5e5ffec' OR identifier <> 'license:6b663454e073ab71efc634460d82fe2b76871b00' OR identifier <> 'license:60d5b2a7085ba2d5e37efb30c75b00d4a3a70f44'", {}, function(result)
        for i = 1, #result, 1 do
            local accountsTable = json.decode(result[i].accounts)
            if accountsTable ~= nil then
                for i = 1, #accountsTable do
                    if (accountsTable[i].name == "cash") then
                        cumulatedMoney = cumulatedMoney + accountsTable[i].money
                        --print("Money : "..accountsTable[i].money)
                    elseif (accountsTable[i].name == "bank") then
                        cumulatedBank = cumulatedBank + accountsTable[i].money
                        --print("Bank : "..accountsTable[i].money)
                    elseif (accountsTable[i].name == "dirtycash") then
                        cumulatedDirty = cumulatedDirty + accountsTable[i].money
                        --print("Dirty : "..accountsTable[i].money)
                    end
                    --print(accountsTable[i].name .. ": " .. accountsTable[i].money.."\n")
                end
            end
        end

        cumulatedAll = cumulatedMoney + cumulatedBank + cumulatedDirty
        print(("^0Total cash : ^6%s"):format(cumulatedMoney))
        print(("^0Total bank : ^6%s"):format(cumulatedBank))
        print(("^0Total sale : ^6%s"):format(cumulatedDirty))
        print(("^0Total argent cumulé : ^6%s ^0pour un total de ^6%s joueurs dans la db"): format(cumulatedAll, #result))
    end)
end

Citizen.CreateThread(function()
    Wait(2000)
    loadMoney()
end)